# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=5000)),
                ('featured_image', models.FileField(upload_to='')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
