# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171127_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
