# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171127_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured_post',
            field=models.BooleanField(default=False),
        ),
    ]
