# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_is_featured_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=1),
            preserve_default=False,
        ),
    ]
