# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('php', 'PHP'), ('arduino', 'Arduino'), ('fiction', 'Fiction'), ('other', 'Other'), ('helping_hand', 'Helping Hands')], max_length=1),
        ),
    ]
